version: '2.1'

services:
  mid-server:
    image: mid-server-london
    build: .
    stop_signal: SIGTERM
    hostname: mid-server
    env_file: .env
    volumes: 
      ["./logs:/opt/agent/logs"]
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1